databases:
  - name: bina-radar-db
    plan: free

services:
  - type: web
    name: bina-radar
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma db push
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bina-radar-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
